[package]
name = "fastagi_router"
version = "0.3.3"
edition = "2021"

[dependencies]
phf = { version = "*", features = ["macros"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
overflow-checks = false
