[globals]
ROUTER=/usr/local/bin/fastagi_router

[sub-dial-pjsip]
exten => s,1,Set(TARGET_CONTACTS=${PJSIP_DIAL_CONTACTS(${ARG1})})
 same => n,GotoIf($[${LEN(${TARGET_CONTACTS})} = 0]?return)
 same => n,Dial(${TARGET_CONTACTS},30,Ttr)
 same => n(return),Return()

[internal]
exten => 501,hint,PJSIP/501
exten => 502,hint,PJSIP/502
exten => 503,hint,PJSIP/503
exten => 504,hint,PJSIP/504
exten => 505,hint,PJSIP/505
exten => 506,hint,PJSIP/506
exten => 507,hint,PJSIP/507
exten => 508,hint,PJSIP/508
exten => 509,hint,PJSIP/509
exten => 510,hint,PJSIP/510
exten => 511,hint,PJSIP/511
exten => 512,hint,PJSIP/512
exten => 513,hint,PJSIP/513
exten => 514,hint,PJSIP/514
exten => 515,hint,PJSIP/515
exten => 516,hint,PJSIP/516
exten => 517,hint,PJSIP/517
exten => 518,hint,PJSIP/518
exten => 519,hint,PJSIP/519
exten => 520,hint,PJSIP/520

exten => 555,1,ConfBridge(555,default_bridge,default_user)
 same => n,Hangup()

exten => _5XX,1,Gosub(sub-dial-pjsip,s,1(${EXTEN}))
 same => n,Hangup()

exten => _[+0-9].,1,AGI(${ROUTER},"in","${EXTEN}")
 same => n,GotoIf($["${LOOKUP_SUCCESS}" = "TRUE"]?local_delivery)
 same => n,AGI(${ROUTER},"out","${EXTEN}","${CALLERID(num)}")
 same => n,GotoIf($["${LOOKUP_SUCCESS}" != "TRUE"]?hang)
 same => n,Set(CALLERID(all)="${DIAL_TRUNK}" <${DIAL_TRUNK}>)
 same => n,Dial(PJSIP/${DIAL_NUMBER}@${DIAL_TRUNK},30,Ttr)
 same => n,Hangup()
 same => n(local_delivery),Gosub(sub-dial-pjsip,s,1(${DIAL_TARGET}))
 same => n(hang),Hangup()

exten => i,1,Hangup()
exten => h,1,Hangup()

[external]
exten => _[+0-9].,1,AGI(${ROUTER},"in","${EXTEN}")
 same => n,GotoIf($["${LOOKUP_SUCCESS}" != "TRUE"]?hang)
 same => n,Set(CALLERID(num)=+${CALLERID(num)})
 same => n,Gosub(sub-dial-pjsip,s,1(${DIAL_TARGET}))
 same => n(hang),Hangup()