[globals]
ROUTER=/usr/local/bin/fastagi_router

[sub-dial-pjsip]
exten => s,1,Set(TARGET_CONTACTS=${PJSIP_DIAL_CONTACTS(${ARG1})})
 same => n,GotoIf($[${LEN(${TARGET_CONTACTS})} = 0]?return)
 same => n,Dial(${TARGET_CONTACTS},30,Ttr)
 same => n(return),Return()

[sub-direct-dial]
exten => s,1,Dial(PJSIP/${ARG1},30,Ttr)
 same => n,Hangup()

[internal]
exten => 73843602313,1,Gosub(sub-direct-dial,s,1(501))
exten => 79235253998,1,Gosub(sub-direct-dial,s,1(501))
exten => 79235254061,1,Gosub(sub-direct-dial,s,1(502))
exten => 73843601773,1,Gosub(sub-direct-dial,s,1(502))
exten => 79235254150,1,Gosub(sub-direct-dial,s,1(503))
exten => 79235254132,1,Gosub(sub-direct-dial,s,1(504))
exten => 73843602414,1,Gosub(sub-direct-dial,s,1(504))
exten => 79235254389,1,Gosub(sub-direct-dial,s,1(505))
exten => 79235254439,1,Gosub(sub-direct-dial,s,1(506))
exten => 73843601771,1,Gosub(sub-direct-dial,s,1(506))
exten => 79235254667,1,Gosub(sub-direct-dial,s,1(507))
exten => 73843600912,1,Gosub(sub-direct-dial,s,1(507))
exten => 79235254706,1,Gosub(sub-direct-dial,s,1(508))
exten => 73843600911,1,Gosub(sub-direct-dial,s,1(508))
exten => 79235255049,1,Gosub(sub-direct-dial,s,1(509))
exten => 73843601331,1,Gosub(sub-direct-dial,s,1(509))
exten => 79235255136,1,Gosub(sub-direct-dial,s,1(510))
exten => 73843601221,1,Gosub(sub-direct-dial,s,1(510))
exten => 79234688941,1,Gosub(sub-direct-dial,s,1(511))
exten => 79234689436,1,Gosub(sub-direct-dial,s,1(512))
exten => 79234693619,1,Gosub(sub-direct-dial,s,1(513))
exten => 79234693746,1,Gosub(sub-direct-dial,s,1(514))
exten => 79234693868,1,Gosub(sub-direct-dial,s,1(515))
exten => 79234698651,1,Gosub(sub-direct-dial,s,1(516))
exten => 79234698906,1,Gosub(sub-direct-dial,s,1(517))
exten => 79234702567,1,Gosub(sub-direct-dial,s,1(518))
exten => 79235069558,1,Gosub(sub-direct-dial,s,1(519))
exten => 79235237068,1,Gosub(sub-direct-dial,s,1(520))

exten => 501,hint,PJSIP/501
exten => 502,hint,PJSIP/502
exten => 503,hint,PJSIP/503
exten => 504,hint,PJSIP/504
exten => 505,hint,PJSIP/505
exten => 506,hint,PJSIP/506
exten => 507,hint,PJSIP/507
exten => 508,hint,PJSIP/508
exten => 509,hint,PJSIP/509
exten => 510,hint,PJSIP/510
exten => 511,hint,PJSIP/511
exten => 512,hint,PJSIP/512
exten => 513,hint,PJSIP/513
exten => 514,hint,PJSIP/514
exten => 515,hint,PJSIP/515
exten => 516,hint,PJSIP/516
exten => 517,hint,PJSIP/517
exten => 518,hint,PJSIP/518
exten => 519,hint,PJSIP/519
exten => 520,hint,PJSIP/520

exten => 555,1,ConfBridge(555,default_bridge,default_user)
 same => n,Hangup()

exten => _5XX,1,Gosub(sub-dial-pjsip,s,1(${EXTEN}))
 same => n,Hangup()

exten => _[+0-9].,1,Set(CALLERID(num)=${FILTER(0-9,${CALLERID(num)})})
 same => n,AGI(${ROUTER},"out","${EXTEN}","${CALLERID(num)}")
 same => n,GotoIf($["${LOOKUP_SUCCESS}" != "TRUE"]?hang)
 same => n,Set(CALLERID(all)="${DIAL_TRUNK}" <${DIAL_TRUNK}>)
 same => n,Dial(PJSIP/${DIAL_NUMBER}@${DIAL_TRUNK},30,Ttr)
 same => n(hang),Hangup()

[external]
exten => _[+0-9].,1,Set(CALLERID(num)=${FILTER(0-9,${CALLERID(num)})})
 same => n,AGI(${ROUTER},"in","${EXTEN}")
 same => n,GotoIf($["${LOOKUP_SUCCESS}" != "TRUE"]?hang)
 same => n,Set(CALLERID(num)=+${CALLERID(num)})
 same => n,Gosub(sub-dial-pjsip,s,1(${DIAL_TARGET}))
 same => n(hang),Hangup()