name: Rust Build and Auto Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo-edit binary
        id: cache-cargo-edit
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-bin-

      - name: Install cargo-edit (Conditional)
        run: |
          if ! command -v cargo-set-version &> /dev/null
          then
              cargo install cargo-edit
          fi

      - name: Cache Cargo dependencies (Clean)
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/release/deps
            target/debug/deps
          key: ${{ runner.os }}-cargo-deps-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-deps-

      - name: Run tests
        run: cargo test --release

      - name: Build release binary
        run: cargo build --release

      - name: Get next release version
        id: get_version
        run: |
          latest=$(gh release list --limit 1 --json tagName -q '.[0].tagName' || echo "v0.0.0")
          
          if [[ "$latest" =~ v([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
            major="${BASH_REMATCH[1]}"
            minor="${BASH_REMATCH[2]}"
            patch="${BASH_REMATCH[3]}"
            
            if [ "$patch" -lt 9 ]; then
              patch=$((patch+1))
            else
              patch=0
              if [ "$minor" -lt 9 ]; then
                minor=$((minor+1))
              else
                minor=0
                major=$((major+1))
              fi
            fi
          else
            major=0
            minor=1
            patch=0
          fi

          next="v${major}.${minor}.${patch}"
          echo "RELEASE_VERSION=$next" >> $GITHUB_ENV
          echo "RELEASE_TAG=$next" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Cargo.toml version
        run: |
          ver=${{ env.RELEASE_VERSION }}
          ver=${ver#v}
          cargo set-version $ver

      - name: Delete all previous releases and tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release list --limit 100 --json tagName --jq '.[].tagName' | while read tag; do
            if [ "$tag" != "${{ env.RELEASE_TAG }}" ]; then
              gh release delete "$tag" --yes || true
              git push --delete origin "$tag" || true
            fi
          done

      - name: Commit Cargo.toml and push tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add Cargo.toml
          git commit -m "Bump version to ${{ env.RELEASE_VERSION }} [skip ci]" || echo "No changes to commit"
          git tag ${{ env.RELEASE_TAG }}
          git push origin main
          git push origin ${{ env.RELEASE_TAG }}

      - name: Create GitHub Release and Upload Binary
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/fastagi_router
          name: Release ${{ env.RELEASE_VERSION }}
          tag_name: ${{ env.RELEASE_TAG }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}